### PR TITLE
Use node way module define

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by lauriro** [comment]
I implemented same thing in different way,
so it preserves also old api when not used in node way

**Comment by ben-eb** [comment]
So in node your solution is to bind your method directly to node? You should only assign module code to `exports` or `module.exports`.

**Comment by lauriro** [comment]
`this` is `exports` in node and `window` in browser

**Comment by ben-eb** [comment]
It's still bad because you have to write:

```js
require('natural-compare-lite').naturalCompare;
```

This is not node-like. You should be able to load it like so:

```js
var naturalCompare = require('natural-compare-lite');
```

**Pull request closed without merging**
